### PR TITLE
Fix code highlighting issues and update linter

### LINKED ISSUE #209: Code Block: no spaces on the right side
**Describe the bug**

There are no spaces on the right side of the code block.

**Expected behavior**

The space on the right side must be the same as the left side.

**Screenshots** https://tailwind-nextjs-starter-blog.vercel.app/blog/new-features-in-v1

image

### PR DESCRIPTION
**Pull request by timlrx**
- Fix #209 
- Fix highlighted code block that does not span the full width when overflow
- Use `span` instead of `div` for code line
- Update linter and fix lint issues

### CODE REVIEW

File: components/analytics/GoogleAnalytics.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ const GAScript = () => {
         src={`https://www.googletagmanager.com/gtag/js?id=${siteMetadata.analytics.googleAnalyticsId}`}
       />
 
-      <Script strategy="lazyOnload">
+      <Script strategy="lazyOnload" id="ga-script">
```
Comment (nguyenyou) [inline components/analytics/GoogleAnalytics.js:13]: Do we need to provide the `id` for the other `<Script />` as well?

Comment (timlrx) [reply components/analytics/GoogleAnalytics.js:13]: It's recommended for inline scripts.

> Inline scripts wrapped with <Script> require an id attribute to be defined to track and optimize the script.

The ones which I modified are those picked up by the linter.
